- name: nginx install and run
  hosts:  web
  become: yes #take subo access
  tasks: 
  - name: install nginx #install
    ansible.builtin.package: # heterongenous module that can work all distrubtion
      name: nginx
      state:  present

  - name: run nginx
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  
  