- name: nginx install and run
  hosts:  web
  tasks: 
  - name: install nginx #install
    ansible.builtin.package: # heterongenous module that can work all distrubtion
      name: nginx
      state:  present
  
  