- name: varialbe to print
  hosts: web
  vars:
    COURSE: "DevOps"
    DURATION: "3months"
    TIMINGS: "morning"
  tasks:
    - name: print the information
      ansible.builtin.debug:
         msg: "Hi , I am learning and practicing {{COURSE}}, duration: {{DURATION}}, timings:{{TIMINGS}}"