- name: varialbe to print
  hosts: web
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "Hi , I am learning and practicing DevOps, duration: 3months, timings:morning"