- name: varialbe to print
  hosts: web
  vars: # play level vars
    COURSE: "DevOps"
    DURATION: "3months"
    TIMINGS: "morning"
  tasks:
    - name: print the information
      ansible.builtin.debug:
         msg: "Hi , I am learning and practicing {{COURSE}}, duration: {{DURATION}}, timings:{{TIMINGS}}"

    - name: print the information
      vars: #task level vars
        COURSE: "DEV+OPSERATIONS" 
      ansible.builtin.debug:
         msg: "Hi , I am learning and practicing {{COURSE}}, duration: {{DURATION}}, timings:{{TIMINGS}}"

    - name: print the information
      ansible.builtin.debug:
         msg: "Hi , I am learning and practicing {{COURSE}}, duration: {{DURATION}}, timings:{{TIMINGS}}"

         