- name: variables from files
  hosts: web
  vars_files:
    - vars.yaml
  tasks:
    name: print the cource inside the message
    ansible.builtin.debug:
      msg: "Hi All, I am learning {{COURSE}}, Duration {{DURATION}} and Timings:{{TIMINGS}}"
 