- name: varialbes from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course
    private: false # not confidentional data
  - name: TRAINER
    prompt: Please enter the Trainer
  - name: DURATION
    prompt: Please enter the Duration
  tasks:
  - name: Print the course information
    ansible.builtin.debug:
        msg: "Hi ,I am learning {{COURSE}} triner:{{TRAINER}} and Duration:{{DURATION}}"