- name: data type information
  hosts: local
  connection: local #for local 
  vars:
    course: "Devops with AWS" #string
    duration: 120days
    topics: #list
    - Linux
    - Shell
    - Ansible
    - Terraform
    - AWS
    - K8
    live: true #boolean
    tools: #ma/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "I am learning {{course}}, with duration: {{duration}}, topcis are:{{topics}},and live: {{live}}, tools are: {{tools}}"
