- name: create user
  hosts: web
  become: yes
  connection: local
  tasks:
    - name: check user exist or not
      ansible.builtin.command: id expense
      register: USER #here USER is a variable that gets output from above command

    - name: print the user informtation
      ansible.builtin.debug:
        msg: "user info: {{USER}}"