- name: demo for filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible')}}"

  - name: covert to uppercase
    vars:
      greeting: "Hello Ganesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"
  
  - name: covert to lowercase
    vars:
      greeting: "Hello Ganesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"
  
    - name: get the unique values
    vars:
      number: [1,2,3,45,6,5,7]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"
  