- name: demo for filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible')}}"

  - name: covert to uppercase
    vars:
      greeting: "Hello Ganesh"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"
  
  - name: covert to lowercase
    vars:
      greeting: "Hello Ganesh"
    ansible.builtin.debug:
      msg: " {{ greeting | lower }}"
  
  - name: get the unique values
    vars:
      numbers: [ 1,2,3,45,6,45,2 ]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"
  
  - name: get the min and max values
    vars:
      numbers: [ 1,2,3,45,6,45,2 ]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max }} "

  - name: convert map to list variables
    vars:
      course:
        name: "DevOps with AWS"
        trainer: "Siva"
        timings: "morning"
    ansible.builtin.debug:
      msg: "{{ course }}"
    
  - name: convert map to list variables
    vars:
      course:
        name: "DevOps with AWS"
        trainer: "Siva"
        timings: "morning"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"
  
  - name: convert map to list variables
    vars:
      course:
        - { "key": "name", "value": "Deveops with AWS" }
        - { "key": "trainer", "value": "ganesh" }
        - { "key": "timings", "value": "morning" }
    ansible.builtin.debug:
        msg: "{{ course | items2dict }}"

  - name: check ip address
    vars:
      myip: " 192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}"

