- name: demo for filters
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('ansible')}}"

  - name: covert to uppercase
    vars:
      greeting: "Hello Ganesh"
    ansible.builtin.debug:
      msg: " {{ greeting | uppder}}"
  
  - name: covert to lowercase
    vars:
      greeting: "Hello Ganesh"
    ansible.builtin.debug:
      msg: " {{ greeting | uppder}}"