- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute the shell
      ansible.builtin.shell: ls -ltr > /tmp/output.txt # login into the server and execute 

- name: check the process
  ansible.builtin.command: ps -ef | grep ssh
  register: output